# Generated by Django 2.2.1 on 2019-05-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_auto_20190514_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='ans',
            field=models.CharField(default='', max_length=100),
        ),
    ]
