# Generated by Django 2.2.1 on 2019-05-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_question_ans'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=50)),
                ('l_name', models.CharField(max_length=50)),
                ('e_mail', models.EmailField(max_length=50)),
                ('m_no', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('addr', models.CharField(max_length=300)),
                ('sex', models.CharField(choices=[('f', 'female'), ('m', 'male')], max_length=20)),
                ('dob', models.DateField()),
            ],
        ),
    ]
