# Generated by Django 2.2.1 on 2019-05-16 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_register'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='addr',
        ),
        migrations.RemoveField(
            model_name='register',
            name='price',
        ),
    ]
