# Generated by Django 2.2.1 on 2019-05-16 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_auto_20190516_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='e_mail',
            field=models.EmailField(max_length=254),
        ),
    ]
